apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    editable: true

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    uid: clickhouse-ds
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      addCorsHeader: true
      defaultDatabase: sandbox
      usePOST: true
    secureJsonData:
      user: default
      password: password123
    editable: true
